import Head from "next/head";
import MainHomePage from "../components/Home/MainHomePage";
import styles from "../styles/Home.module.css";
import { NextSeo } from "next-seo";
import screenshot from "../images/portfolio.png";

export default function Home() {
  return (
    <>
      <NextSeo
        title="Chi_Dev Portfolio"
        description="This is My portfolio shocasing my projects"
        canonical="https://www.canonical.ie/"
        openGraph={{
          url: "https://www.url.ie/a",
          title: "Chi_Dev Portfolio",
          description: "Open Graph Description",
          images: [
            {
              url: screenshot,
              width: 800,
              height: 600,
              alt: "Og Image Alt",
              type: "image/jpeg",
            },
            ,
            { url: screenshot },
          ],
          site_name: "SiteName",
        }}
        twitter={{
          handle: "@ChibuikeNnaji10",
          site: "@ChibuikeNnaji10",
          cardType: "summary_large_image",
        }}
      />
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHomePage />
    </>
  );
}
